source "https://rubygems.org"

ruby "3.2.3"

gem "rails", "~> 7.1.5", ">= 7.1.5.1"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "jbuilder"
gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "bootsnap", require: false
gem "rack-cors"
gem 'httparty'
gem 'sidekiq', '~> 7.2'
gem 'sidekiq-scheduler'
gem 'dotenv-rails', groups: [:development, :test]

group :development, :test do
  gem "debug", platforms: %i[ mri windows ]
  gem "rspec-rails"
end